### ISSUE TITLE
Final group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by keroloussamy** [keroloussamy/Hotelzilla-api#24]
Final group capstone project : [Link](https://github.com/keroloussamy/Hotelzilla-api/projects/1) 

@Anjacodes 
@gemmen29 
@keroloussamy 
@Lucas-Masaba 
@williamrolando88 

<img width="1398" alt="Screen Shot 2022-05-04 at 15 37 41" src="https://user-images.githubusercontent.com/75140420/166821799-a532f46b-eb63-4027-bf82-1f99fa8c84be.png">

**Comment by MuriloRoque** [comment]
Hi @keroloussamy, @gemmen29, @Lucas-Masaba, @williamrolando88, @Anjacodes,

Good job so far!
There are some issues that you still need to work on but you are almost there!

## Suggested changes

- [x] Please put a screenshot of your Kanban board in this issue's description, just like it's mentioned in [the requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md).

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Anjacodes** [comment]
Hi @MuriloRoque , 
Thank you for your feedback! 🙏 We have added a screenshot into the description of the issue now!

**Comment by MuriloRoque** [comment]
Hi @keroloussamy, @Anjacodes, @gemmen29, @Lucas-Masaba, @williamrolando88,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
